name: Python CI
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run Tests
              run: pytest
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/python-3.11@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                command: test
                args: --file=requirements.txt